Targets on bg layer and refactor of views and controller
clp-research/golmi pull request #32
Opened 2022-01-16 15:12 UTC by kfriedrichs

I created this branch to change the layer targets are drawn to but then couldn't stop myself to fix some style issues and remove the "fix highlights" todo, so the branch name is not really fitting unfortunately.

**Target drawing changes**
* targets are now on background layer: in contrast to objects, targets will probably not change during the interaction for most use cases, therefore it's nicer not to redraw them every time the object layer changes
* added a hook onUpdateTargets (not currently used but for completeness)
* updated the LayerView class documentation accordingly
* pentomino demo interface now contains targets again because it seemed a little empty and boring before, but I'm definitely open to objections here

**Highlight todo**
* removed the old 'fix highlights' todo: now the style applied in order to draw highlights is reset at the end of the function, this way the (not planned for) gripper highlight is gone, too. In a larger refactor it might be nice not to apply style options for each line / break everything down into smaller functions. The drawing code is one of the first things I wrote for Golmi and it shows.

**Style**
* converted tabs to spaces for controller and views
* shortened lines in LayerView
* no more one-line if-clauses

**Removed pentoDemo.js**
* this sneaky file somehow managed to stay in the repository until now

2022-01-17 13:51 UTC, phisad requested changes
Looks like `this.targets` should be fixed; others are minor issues

2022-01-17 13:51 UTC, phisad commented on app/static/js/view/LayerView.js
> +			for (const target of Object.values(this.targets))	{
As it seems, this shouldnt be here, because LayerView cannot know that there are target (this.targets) is never set in the constructor.

2022-01-17 13:51 UTC, phisad commented on app/static/js/view/LayerView.js
> +						if (r == 0 || !(bMatrix[r-1][c])) {
Is there a nicer boolean expression for this `!(bMatrix[r-1][c])`? IsUpperBorder?

2022-01-17 13:51 UTC, phisad commented on app/pentomino/static/js/pentomino.js
> +                                        "create_targets": true,
Can be combine `create_targets` and `area_targets` e.g. `create_targets = "bottom"`?

2022-01-23 16:32 UTC, kfriedrichs commented on app/static/js/view/LayerView.js
> +			for (const target of Object.values(this.targets))	{
this.targets is defined in the parent class (View) constructor, just like the other drawables (objs, grippers), so this shouldn't be an issue

2022-01-23 16:37 UTC, kfriedrichs commented on app/pentomino/static/js/pentomino.js
> +                                        "create_targets": true,
That's something has bugged me before. I created an issue and will take care of it.

2022-01-23 17:37 UTC, kfriedrichs commented on app/static/js/view/LayerView.js
> +						if (r == 0 || !(bMatrix[r-1][c])) {
The most recent commits adds some small functions for more readability here.

2022-01-24 09:57 UTC, phisad commented on app/static/js/view/LayerView.js
> +			for (const target of Object.values(this.targets))	{
Okey, alright, looks like I missed that. So View says that there might be "some targets" and LayerView expects that these are Obj. The View just provides us some infrastructure to handle the events.

2022-01-24 09:58 UTC, phisad approved these changes
Looks good now.

2022-01-24 10:49 UTC, merged