Newstate
clp-research/golmi pull request #34
Opened 2022-01-23 12:29 UTC by sebag90

1. The Grids (object and targets) have been moved to the state since that's where the objects and targets are saved. The init method has been modified to automatically generate a state given dictionaries containing objects and targets as opposed to before where an empty state was generated. A class method was implemented to still generate an empty state if needed. The State can now interact directly with the grids (erase and plot all objects)
2. PEP8

2022-01-24 07:42 UTC, kfriedrichs requested changes
Very nice, this looks so much cleaner now.

Definitely need to carefully resolve the conflicts with main or even merge main into newstate first: the connection / client model generation in `app/app.py` changed a lot with the introduction of a room_manager.

I would also suggest encapsulating the grid functions by adding corresponding calling functions in the State, because at this point the dependencies are getting scary, e.g. 
```self.model.state.object_grid.gripper_on_grid(new_gr_pos)```
in Mover.

2022-01-24 07:42 UTC, kfriedrichs commented on model/generator.py
> +            self, target_grid, index, piece_type,
Why remove the type annotations here? In this case the type is already in the parameter name but I vote to keep the specification anyway, just in case the name changes at some point.

2022-01-24 07:42 UTC, kfriedrichs commented on model/generator.py
> +    def _generate_objects(self, n_objs, area_block, area_target, create_tgts):
see above

2022-01-24 07:42 UTC, kfriedrichs commented on model/generator.py
>          #  - BoardGenerator
I think we can remove this TODO

2022-01-24 07:42 UTC, kfriedrichs commented on model/model.py
> +            # replot objects and targets, just to be sure
> just to be sure

what does that mean? :'D

2022-01-24 07:42 UTC, kfriedrichs commented on model/model.py
> +                    self.state.object_grid.remove_obj(obj)
We could encapsulate this in a state.remove_obj function.

2022-01-24 11:12 UTC, phisad reviewed
Please review the comments. There were useful suggestions by @kfriedrichs We should fix the conflicts first.

2022-01-24 11:12 UTC, phisad commented on model/generator.py
> +            self, target_grid, index, piece_type,
Second that

2022-01-24 11:12 UTC, phisad commented on app/register_experiments.py
> +            pentomino.apply_config_to
Is this "wrap each line" a PEP8 default? Otherwise we might want to share the formatter.

2022-01-24 11:12 UTC, phisad commented on app/app.py
>  client_models = dict()
This is not used anymore, but `room_manager` The branch migth require a merge from main.

2022-01-24 11:12 UTC, phisad commented on model/model.py
> +        tile = self.state.object_grid.get_single_tile({"x": x, "y": y})
Same here `state.get_obj_at(x,y)`

2022-01-24 11:12 UTC, phisad commented on model/mover.py
> +        obj_can_move = self.model.state.object_grid.is_legal_position(
The re-occurrence suggests actually that model == state? I am thinking to renamed model to "golmi". Then we would have "golmi.state" and "golmi.room". We could rename state to model, but I think state is just fine.

2022-01-25 21:28 UTC, sebag90 commented on model/generator.py
> +            self, target_grid, index, piece_type,
I removed it because it's not very consistent with the rest of the project (or the other arguments of the functions) where we never used type hints. An alternative would be to add it to the docstring? We should definitely discuss and agree on a coding style to keep the project consistent.

2022-01-25 21:28 UTC, sebag90 commented on model/generator.py
>          #  - BoardGenerator
:+1:

2022-01-25 21:30 UTC, sebag90 commented on model/model.py
> +            # replot objects and targets, just to be sure
better be safe than sorry :sweat_smile:  technically it should never ever happens that a state with empty grids is passed to the model, but it is however possible by instantiating an empty state and adding objects manually (shouldn't be done!). I just wanted to avoid this scenario by re-plotting the objects and targets after a state is passed to the model

2022-01-25 21:32 UTC, sebag90 commented on model/model.py
> +                    self.state.object_grid.remove_obj(obj)
very good! I would expect however, that such function will also remove the object from the respective dictionary (but since it's O(1) that should not be a problem). I will also implement the state.add_obj() function

2022-01-25 21:36 UTC, sebag90 commented on app/register_experiments.py
> +            pentomino.apply_config_to
not really, it's just a way to avoid [lines over 79 characters](https://www.python.org/dev/peps/pep-0008/#maximum-line-length). I don't use a formatter, just a linter, but it would be a good idea to agree on a style and a formatter. I've believe that [black](https://github.com/psf/black) is the most popular for python.

2022-01-25 21:36 UTC, sebag90 commented on app/app.py
>  client_models = dict()
:+1:

2022-01-25 21:37 UTC, sebag90 commented on model/model.py
> +        tile = self.state.object_grid.get_single_tile({"x": x, "y": y})
:+1:

2022-01-25 21:43 UTC, sebag90 commented on model/mover.py
> +        obj_can_move = self.model.state.object_grid.is_legal_position(
I would keep the state under its current name: State since it's quite intuitive. The model, as far as I understand it, is responsible to modify the state, but should not retain any information about it.

2022-01-26 12:44 UTC, phisad commented on model/generator.py
> +            self, target_grid, index, piece_type,
Agreed, I would support type hints as a good practice, but we should decide on this together. The consistency is a bit hard to achieve as I would see adding type hints as an ongoing process

2022-01-26 12:53 UTC, phisad commented on model/model.py
> +                    self.state.object_grid.remove_obj(obj)
Is this implemented in this PR?

2022-01-27 08:44 UTC, kfriedrichs approved these changes
I'm good with this now. Not sure if the extra encapsulation is going to happen here or in a different PR?

2022-01-28 20:18 UTC, sebag90 commented on model/model.py
> +                    self.state.object_grid.remove_obj(obj)
I implemented the functions on the state side, but it is a bit soon to adapt everything on the mover. The problem is that a lot of functions to move objects rely on the id of the object to access it through the dictionary to then apply the movement (and by removing the object from the dictionary these functions obviously fail). We should change the functions to operate directly on the object itself. I think this is too big for this PR, but will work on it on the next one.

2022-01-28 20:28 UTC, sebag90 commented
I already implemented the extra functions in this PR on the state side, but as I said in a comment, I will work on changing the endpoints on the mover in a separate PR.

2022-01-29 09:33 UTC, kfriedrichs approved these changes
The new functions in State look good. Doing more cleanup in another PR seems fair. Let's merge this!

2022-01-29 09:37 UTC, merged